import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Favicon from "./favicon.ico";
import { Providers } from "@/redux/Providers";
import Header from "@/components/Header";
import Authprovider from "@/components/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Amazon Clone",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: Favicon.src }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ backgroundColor: "rgb(243 244 246)" }}
      >
        <Providers>
          <Authprovider>
            <Header />
            {children}
          </Authprovider>
        </Providers>
      </body>
    </html>
  );
}
